site_name: Deep Java Library
repo_name: awslabs/djl
repo_url: https://github.com/awslabs/djl/
site_url: https://djl.ai
use_directory_urls: false
markdown_extensions:
  - codehilite
  - toc:
      permalink: true
theme:
  name: material
  logo: website/img/DJL.svg
  favicon: website/img/favicon.png
  features:
    - tabs
  palette:
    primary: light-blue
    accent: light-blue
google_analytics:
  - UA-159559852-2
  - auto
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/awslabs/djl
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/deepjavalibrary
    - icon: fontawesome/brands/slack
      link: https://deepjavalibrary.slack.com/
    - icon: fontawesome/brands/zhihu
      link: https://zhuanlan.zhihu.com/c_1255493231133417472
docs_dir: '../'
plugins:
  - search
  - mknotebooks
  - exclude:
      regex:
        - '.*\.(symbol|params|pt|jar|gz|zip|txt|json|sh|bat|cmd|puml|g4|java|py|cc|h|pro|properties|xml|gradlew|gradle|Dockerfile|RepositoryFactory|EngineProvider|ZooProvider)$|(docker|integration|testing|tools)/.*$'
nav:
  - HOME: 'README.md'
  - 'docs/quick_start.md'
  - 'docs/interactive_tool.md'
  - 'docs/README.md'
  - 'examples/README.md'
  - 'docs/development/README.md'
  - 'docs/faq.md'
  - User manual:
      - 'docs/development/setup.md'
      - 'docs/model-zoo.md'
      - 'docs/dataset.md'
      - 'docs/load_model.md'
      - 'docs/development/configure_logging.md'
      - 'docs/development/cache_management.md'
      - 'docs/development/memory_management.md'
      - 'docs/development/how_to_use_dataset.md'
      - 'docs/how_to_collect_metrics.md'
      - 'docs/development/troubleshooting.md'
  - MXNet:
      - Overview: 'mxnet/README.md'
      - MXNet Engine: 'mxnet/mxnet-engine/README.md'
      - MXNet Model Zoo: 'mxnet/mxnet-model-zoo/README.md'
      - MXNet native library: 'mxnet/native/README.md'
      - Import Gluon Model: 'docs/mxnet/how_to_convert_your_model_to_symbol.md'
  - ONNX Runtime:
      - Overview: 'onnxruntime/onnxruntime-engine/README.md'
      - ONNX runtime Hybrid Engine: 'docs/onnxruntime/hybrid_engine.md'
  - PyTorch:
      - Overview: 'pytorch/README.md'
      - PyTorch Engine: 'pytorch/pytorch-engine/README.md'
      - PyTorch Model Zoo: 'pytorch/pytorch-model-zoo/README.md'
      - Pytorch native library: 'pytorch/pytorch-native/README.md'
      - Import PyTorch Model: 'docs/pytorch/how_to_convert_your_model_to_torchscript.md'
      - Inference performance tuning: 'docs/pytorch/how_to_optimize_inference_performance.md'
  - TensorFlow:
      - Overview: 'tensorflow/README.md'
      - TensorFlow Engine: 'tensorflow/tensorflow-engine/README.md'
      - TensorFlow Model Zoo: 'tensorflow/tensorflow-model-zoo/README.md'
      - Import Keras Model: 'docs/tensorflow/how_to_import_keras_models_in_DJL.md'
  - Utilities:
      - Android: 'android/README.md'
      - AWS S3 support: 'extensions/aws-ai/README.md'
      - Hadoop support: 'extensions/hadoop/README.md'
