name: publish android native

on:
  # To trigger this workflow manually, you can use the following curl command:
  # curl -XPOST -u "USERNAME:PERSONAL_TOKEN" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/awslabs/djl/dispatches --data '{"event_type": "pytorch-android-native-build"}'

  # Make sure you create your personal token with repo access. Follow steps in
  # https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
  # to create your personal token.
  repository_dispatch:
    types: [pytorch-android-native-build]

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        format: ["armeabi-v7a", "arm64-v8a", "x86" ,"x86_64"]
    env:
      PYTORCH_TAG_VERSION:    "v1.5.0"
      PYTORCH_VERSION: "1.5.0"
      NDK_VERSION: "20.0.5594570"
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Python3
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - name: clone pytorch
        run: git clone https://github.com/pytorch/pytorch android_pytorch_tmp -b "${PYTORCH_TAG_VERSION}" --recursive
      - name: install Python Dependencies
        run: pip install numpy ninja pyyaml mkl mkl-include setuptools cmake cffi
      - name: Install NDK
        run: echo "y" | sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;${NDK_VERSION}" --sdk_root=${ANDROID_SDK_ROOT}
      - name: build android
        run: |
          export ANDROID_NDK=${ANDROID_HOME}/ndk-bundle
          export ANDROID_ABI=${{ matrix.format }}
          cd android_pytorch_tmp
          bash ./scripts/build_android.sh
          cd build_android/install
          zip -r ${{ matrix.format }}_native.zip include lib
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
        run: |
          aws s3 cp android_pytorch_tmp/build_android/install/${{ matrix.format }}_native.zip s3://djl-ai/publish/pytorch-${PYTORCH_VERSION}/android_native/
