name: continuous build

on:
  push:
    paths-ignore:
      - "**.md"
      - "**.ipynb"
      - "**.json"
      - "**.html"
      - "**.js"
      - "**.css"
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.ipynb"
      - "**.json"
      - "**.html"
      - "**.js"
      - "**.css"

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      # Enable gradle cache: https://github.com/actions/cache/blob/master/examples.md#java---gradle
      - uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: check disk space
        run: df -h
      - name: Build with Gradle
        run: ./gradlew build jRR
      - name: API test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: api
          path: api/build/reports
      - name: basicdataset test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: basicdataset
          path: basicdataset/build/reports
      - name: examples test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: examples
          path: examples/build/reports
      - name: integration test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: integration
          path: integration/build/reports
      - name: model-zoo test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: model-zoo
          path: model-zoo/build/reports
      - name: mxnet-engine test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mxnet-engine
          path: mxnet/mxnet-engine/build/reports
      - name: mxnet-model-zoo test results
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: mxnet-model-zoo
          path: mxnet/mxnet-model-zoo/build/reports
