name: D2L book Notebook integration tests

on:
  push:
    paths:
      - "jupyter/d2l-java/**"
  pull_request:
    paths:
      - "jupyter/d2l-java/**"

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        group: ["CH1_CH4_DROPOUT", "CH4_MID", "CH4_REST", "REST"]
    env:
      CH1_CH4_DROPOUT: "chapter_installation chapter_introduction chapter_preface chapter_preliminaries chapter_notation dropout.ipynb"
      CH4_MID: "underfit-overfit.ipynb mlp-djl.ipynb"
      CH4_REST: "mlp-scratch.ipynb backprop.ipynb environment.ipynb mlp.ipynb numerical-stability-and-init.ipynb weight-decay.ipynb"
      REST: "chapter_convolutional-neural-networks chapter_linear-networks chapter_optimization utils"
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: actions/checkout@v2
      - name: Set up Python3
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install IJava kernel
        run: |
          pip3 install jupyter
          git clone https://github.com/frankfliu/IJava.git
          cd IJava/
          ./gradlew installKernel
      - name: test Notebook
        run: |
          cd jupyter/d2l-java
          bash test_notebook.sh $${{ matrix.group }}
      - name: generated Notebook in html
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: notebook
          path: jupyter/d2l-java/test_output/
